services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    dns:
      - 85.193.93.193
      - 85.193.93.194
    environment:
      PORT: 3001
      FRONTEND_ORIGIN: https://pixipod.ru
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}

  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    dns:
      - 85.193.93.193
      - 85.193.93.194
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
